api:
  base_url: "https://httpbin.org"

database:
  mysql:
    host: "localhost"
    port: 3306
    user: "test_user"
    password: "test_password"
    database: "test_db"
  
  mongodb:
    host: "localhost"
    port: 27017
    database: "test_db"
    username: "test_user"
    password: "test_password"

redis:
  host: "localhost"
  port: 6379
  db: 0 